Visual:
  config_path: "YOLO-World/configs/image_prompts/yolo_world_v2_l_vlpan_bn_2e-4_80e_8gpus_image_prompt_demo.py"
  model_path: "weights/yolo_world_v2_l_image_prompt_adapter-719a7afb.pth"
  work_dir: "output/"

Text:
  font_path: "PaddleOCR/doc/fonts/simfang.ttf"
